"""init_db_tables

Revision ID: 9f3dfd8e46f2
Revises: 
Create Date: 2026-01-31 02:39:48.325126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9f3dfd8e46f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PEDOMETER', 'PHOTO', 'LOCATION', 'INTERACTION', 'COGNITIVE', name='questtype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_metadata', sa.JSON(), nullable=True),
    sa.Column('reward_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_definitions_type'), 'quest_definitions', ['type'], unique=False)
    op.create_table('store_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='itemrarity'), nullable=False),
    sa.Column('category', sa.Enum('OUTFIT', 'HEAD', 'HAND', 'BACKGROUND', 'CONSUMABLE', name='itemcategory'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_amount', sa.Integer(), nullable=False),
    sa.Column('currency_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_items_category'), 'store_items', ['category'], unique=False)
    op.create_index(op.f('ix_store_items_rarity'), 'store_items', ['rarity'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('real_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gendertype'), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('address_district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'GUARDIAN', 'B2G_ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'B2C_BASIC', 'B2C_PREMIUM', 'B2G_WELFARE', name='usertier'), nullable=False),
    sa.Column('daily_usage', sa.Integer(), nullable=False),
    sa.Column('last_usage_reset_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sa.Enum('ANDROID', 'IOS', 'WEB', name='platformtype'), nullable=False),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('fcm_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_fcm_token'), 'users', ['fcm_token'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tier'), 'users', ['tier'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_refresh_token'), 'auth_sessions', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('USER', 'AI', name='speakertype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_consented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_is_consented'), 'conversations', ['is_consented'], unique=False)
    op.create_index(op.f('ix_conversations_speaker'), 'conversations', ['speaker'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('guardian_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardian_relations_guardian_id'), 'guardian_relations', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_guardian_relations_ward_id'), 'guardian_relations', ['ward_id'], unique=False)
    op.create_table('legacy_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('USER', 'AI', name='speakertype'), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'IGNORED', name='processingstatus'), nullable=False),
    sa.Column('error_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_queue_speaker'), 'legacy_queue', ['speaker'], unique=False)
    op.create_index(op.f('ix_legacy_queue_status'), 'legacy_queue', ['status'], unique=False)
    op.create_table('life_legacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('EPISODE', 'VALUE', name='legacycategory'), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_legacies_category'), 'life_legacies', ['category'], unique=False)
    op.create_index(op.f('ix_life_legacies_user_id'), 'life_legacies', ['user_id'], unique=False)
    op.create_table('quest_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'REWARDED', 'FAILED', 'EXPIRED', name='queststatus'), nullable=False),
    sa.Column('proof_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quest_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_logs_user_id'), 'quest_logs', ['user_id'], unique=False)
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_time', sa.Time(), nullable=False),
    sa.Column('repeat_days', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_trigger_time'), 'routines', ['trigger_time'], unique=False)
    op.create_index(op.f('ix_routines_type'), 'routines', ['type'], unique=False)
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    op.create_table('safety_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.Enum('DEPRESSION', 'DEMENTIA', 'SUICIDE', 'SCAM', 'EMERGENCY', name='risktype'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('detected_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_logs_risk_type'), 'safety_logs', ['risk_type'], unique=False)
    op.create_index(op.f('ix_safety_logs_user_id'), 'safety_logs', ['user_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('social_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_provider'), 'social_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_social_accounts_social_id'), 'social_accounts', ['social_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_table('subscription_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('WEB_PG', 'ONE_STORE', 'GALAXY_STORE', name='paymentmethod'), nullable=False),
    sa.Column('payer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('terms_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('terms_of_service', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy', sa.Boolean(), nullable=False),
    sa.Column('sensitive_info_agreement', sa.Boolean(), nullable=False),
    sa.Column('cross_border_transfer', sa.Boolean(), nullable=False),
    sa.Column('third_party_provision', sa.Boolean(), nullable=False),
    sa.Column('marketing', sa.Boolean(), nullable=False),
    sa.Column('terms_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agreed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_agreements_user_id'), 'terms_agreements', ['user_id'], unique=False)
    op.create_table('user_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_persona', sa.Enum('SIA_MALE', 'SIA_FEMALE', name='personatype'), nullable=False),
    sa.Column('user_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('axis_playful', sa.Float(), nullable=False),
    sa.Column('axis_feisty', sa.Float(), nullable=False),
    sa.Column('axis_dependent', sa.Float(), nullable=False),
    sa.Column('axis_caregive', sa.Float(), nullable=False),
    sa.Column('axis_reflective', sa.Float(), nullable=False),
    sa.Column('user_profile', sa.JSON(), nullable=True),
    sa.Column('last_summary', sa.JSON(), nullable=True),
    sa.Column('legacy_progress', sa.JSON(), nullable=True),
    sa.Column('avatar_state', sa.JSON(), nullable=True),
    sa.Column('touch_script_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['store_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_inventory_user_id'), 'user_inventory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_inventory_user_id'), table_name='user_inventory')
    op.drop_table('user_inventory')
    op.drop_table('user_context')
    op.drop_index(op.f('ix_terms_agreements_user_id'), table_name='terms_agreements')
    op.drop_table('terms_agreements')
    op.drop_table('subscription_logs')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_social_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_provider'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_safety_logs_user_id'), table_name='safety_logs')
    op.drop_index(op.f('ix_safety_logs_risk_type'), table_name='safety_logs')
    op.drop_table('safety_logs')
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_type'), table_name='routines')
    op.drop_index(op.f('ix_routines_trigger_time'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_quest_logs_user_id'), table_name='quest_logs')
    op.drop_table('quest_logs')
    op.drop_index(op.f('ix_life_legacies_user_id'), table_name='life_legacies')
    op.drop_index(op.f('ix_life_legacies_category'), table_name='life_legacies')
    op.drop_table('life_legacies')
    op.drop_index(op.f('ix_legacy_queue_status'), table_name='legacy_queue')
    op.drop_index(op.f('ix_legacy_queue_speaker'), table_name='legacy_queue')
    op.drop_table('legacy_queue')
    op.drop_index(op.f('ix_guardian_relations_ward_id'), table_name='guardian_relations')
    op.drop_index(op.f('ix_guardian_relations_guardian_id'), table_name='guardian_relations')
    op.drop_table('guardian_relations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_speaker'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_consented'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_token'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_tier'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_fcm_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_store_items_rarity'), table_name='store_items')
    op.drop_index(op.f('ix_store_items_category'), table_name='store_items')
    op.drop_table('store_items')
    op.drop_index(op.f('ix_quest_definitions_type'), table_name='quest_definitions')
    op.drop_table('quest_definitions')
    # ### end Alembic commands ###
